services:
  backend:
    build: ./
    command: poetry run ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - 5173:5173
    env_file:
      - ./.env