# Generated by Django 5.2.4 on 2025-07-16 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Peak",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("aliases", models.TextField(blank=True)),
                ("dominance_peak", models.CharField(blank=True, max_length=255)),
                ("dominance_distance", models.FloatField()),
                ("prominence_distance", models.FloatField()),
                ("prominence_peak", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(max_length=255)),
                ("elevation", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(unique=True)),
                (
                    "peak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="peakquiz.peak"
                    ),
                ),
            ],
        ),
    ]
