# Generated by Django 5.2.4 on 2025-07-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peakquiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peak",
            name="dominance_peak",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="peak",
            name="prominence_peak",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
