# Generated by Django 5.2.4 on 2025-07-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peakquiz", "0002_alter_peak_dominance_peak_alter_peak_prominence_peak"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peak",
            name="aliases",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="peak",
            name="dominance_distance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="peak",
            name="elevation",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="peak",
            name="prominence_distance",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="peak",
            name="region",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
